
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8
    username: maling
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      servlet:
        url-mappings: /druid/*
        login-username: druid
        login-password: druid
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  session:
    timeout: 1